

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" \
    -where "municipal IN ('CAMBRIDGE', 'SOMERVILLE', 'BOSTON', 'MEDFORD', 'ARLINGTON', 'NEWTON','WATERTOWN', 'BELMONT', 'EVERETT', 'CHELSEA', 'MALDEN','WINTHROP', 'BROOKLINE')" \
    data/grid_attr_filtBOS2.geojson ../../proc/grid_250m_shell_smaller_data.shp


ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" \
    data/grid_attr_MA.geojson ../../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326"\
    -where "municipal IN ('CAMBRIDGE', 'SOMERVILLE', 'BOSTON', 'MEDFORD', 'ARLINGTON', 'NEWTON','WATERTOWN', 'BELMONT', 'EVERETT', 'CHELSEA', 'MALDEN','WINTHROP', 'BROOKLINE', 'MELROSE', 'SAUGUS', 'LYNN', 'WINCHESTER', 'LEXINGTON', 'WALTHAM', 'REVERE', 'WESTON', 'WELLESLEY', 'NEEDHAM', 'DOVER','DEDHAM','MILTON', 'QUINCY', 'BRAINTREE','WEYMOUTH', 'WAKEFIELD','WOBURN','PEABODY','SALEM','MARBLEHEAD', 'SWAMPSCOTT', 'BEVERLY','BURLINGTON','BEDFORD','LINCOLN', 'CONCORD','WAYLAND','NATICK', 'STONEHAM','NORWOOD','WESTWOOD', 'CANTON','RANDOLPH', 'NAHANT')" \
    data/grid_attr_filtBOS4.geojson ../../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326"\
    -where "municipal IN ('CAMBRIDGE', 'SOMERVILLE', 'BOSTON', 'MEDFORD', 'ARLINGTON', 'NEWTON','WATERTOWN', 'BELMONT', 'EVERETT', 'CHELSEA', 'MALDEN','WINTHROP', 'BROOKLINE', 'MELROSE', 'SAUGUS', 'LYNN', 'WINCHESTER', 'LEXINGTON', 'WALTHAM', 'REVERE', 'WESTON', 'WELLESLEY', 'NEEDHAM', 'DOVER','DEDHAM','MILTON', 'QUINCY', 'BRAINTREE','WEYMOUTH', 'WAKEFIELD','WOBURN','PEABODY','SALEM','MARBLEHEAD', 'SWAMPSCOTT', 'BEVERLY','BURLINGTON','BEDFORD','LINCOLN', 'CONCORD','WAYLAND','NATICK', 'STONEHAM','NORWOOD','WESTWOOD', 'CANTON','RANDOLPH', 'NAHANT')" \
    data/grid_attr_filtBOSMetro.geojson ../proc/grid_250m_shell_smaller_data.shp


ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326"\
     data/zip_attr.geojson ../proc/zips_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326"\
 -where "municipal IN ('ADAMS','ALFORD','BECKET','CHESHIRE','CLARKSBURG','DALTON','EGREMONT','FLORIDA','GREAT BARRINGTON','HANCOCK','HINSDALE','LANESBOROUGH','LEE','LENOX','MONTEREY','MOUNT WASHINGTON','NEW ASHFORD','NEW MARLBOROUGH','NORTH ADAMS','OTIS','PERU','PITTSFIELD','RICHMOND','SANDISFIELD','SAVOY','SHEFFIELD','STOCKBRIDGE','TYRINGHAM','WASHINGTON','WEST STOCKBRIDGE','WILLIAMSTOWN','WINDSOR')" \
    data/grid_attr_filtBRPC.geojson ../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('BARNSTABLE','BOURNE','BREWSTER','CHATHAM','DENNIS','EASTHAM','FALMOUTH','HARWICH','MASHPEE','ORLEANS','PROVINCETOWN','SANDWICH','TRURO','WELLFLEET','YARMOUTH','AQUINNAH','CHILMARK','EDGARTOWN','GOSNOLD','OAK BLUFFS','TISBURY','WEST TISBURY','NANTUCKET')" data/grid_attr_filtCape.geojson ../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('ABINGTON','AVON','BRIDGEWATER','BROCKTON','EAST BRIDGEWATER','EASTON','HALIFAX','HANSON','KINGSTON','PEMBROKE','PLYMOUTH','PLYMPTON','STOUGHTON','WEST BRIDGEWATER','WHITMAN','ACUSHNET','ATTLEBORO','BERKLEY','CARVER','DARTMOUTH','DIGHTON','FAIRHAVEN','FALL RIVER','FREETOWN','LAKEVILLE','MANSFIELD','MARION','MATTAPOISETT','MIDDLEBOROUGH','NEW BEDFORD','NORTH ATTLEBOROUGH','NORTON','PLAINVILLE','RAYNHAM','REHOBOTH','ROCHESTER','SEEKONK','SOMERSET','SWANSEA','TAUNTON','WAREHAM','WESTPORT', 'BARNSTABLE','BOURNE','BREWSTER','CHATHAM','DENNIS','EASTHAM','FALMOUTH','HARWICH','MASHPEE','ORLEANS','PROVINCETOWN','SANDWICH','TRURO','WELLFLEET','YARMOUTH','AQUINNAH','CHILMARK','EDGARTOWN','GOSNOLD','OAK BLUFFS','TISBURY','WEST TISBURY','NANTUCKET')" data/grid_attr_filtSoutheast.geojson ../proc/grid_250m_shell_smaller_data.shp


ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('AMESBURY','ANDOVER','BOXFORD','GEORGETOWN','GROVELAND','HAVERHILL','LAWRENCE','MERRIMAC','METHUEN','NEWBURY','NEWBURYPORT','NORTH ANDOVER','ROWLEY','SALISBURY','WEST NEWBURY','BILLERICA','CHELMSFORD','DRACUT','DUNSTABLE','LOWELL','PEPPERELL','TEWKSBURY','TYNGSBOROUGH','WESTFORD')" data/grid_attr_filtNortheast.geojson ../proc/grid_250m_shell_smaller_data.shp


ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('ACTON','ARLINGTON','ASHLAND','BEDFORD','BELLINGHAM','BELMONT','BEVERLY','BOLTON','BOSTON','BOXBOROUGH','BRAINTREE','BROOKLINE','BURLINGTON','CAMBRIDGE','CANTON','CARLISLE','CHELSEA','COHASSET','CONCORD','DANVERS','DEDHAM','DOVER','DUXBURY','ESSEX','EVERETT','FOXBOROUGH','FRAMINGHAM','FRANKLIN','GLOUCESTER','HAMILTON','HANOVER','HINGHAM','HOLBROOK','HOLLISTON','HOPKINTON','HUDSON','HULL','IPSWICH','LEXINGTON','LINCOLN','LITTLETON','LYNN','LYNNFIELD','MALDEN','MANCHESTER','MARBLEHEAD','MARLBOROUGH','MARSHFIELD','MAYNARD','MEDFIELD','MEDFORD','MEDWAY','MELROSE','MIDDLETON','MILFORD','MILLIS','MILTON','NAHANT','NATICK','NEEDHAM','NEWTON','NORFOLK','NORTH READING','NORWELL','NORWOOD','PEABODY','QUINCY','RANDOLPH','READING','REVERE','ROCKLAND','ROCKPORT','SALEM','SAUGUS','SCITUATE','SHARON','SHERBORN','SOMERVILLE','SOUTHBOROUGH','STONEHAM','STOW','SUDBURY','SWAMPSCOTT','TOPSFIELD','WAKEFIELD','WALPOLE','WALTHAM','WATERTOWN','WAYLAND','WELLESLEY','WENHAM','WESTON','WESTWOOD','WEYMOUTH','WILMINGTON','WINCHESTER','WINTHROP','WOBURN','WRENTHAM')" data/grid_attr_filtMAPC.geojson ../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('AUBURN','BARRE','BERLIN','BLACKSTONE','BOYLSTON','BROOKFIELD','CHARLTON','DOUGLAS','DUDLEY','EAST BROOKFIELD','GRAFTON','HARDWICK','HOLDEN','HOPEDALE','LEICESTER','MENDON','MILLBURY','MILLVILLE','NEW BRAINTREE','NORTH BROOKFIELD','NORTHBOROUGH','NORTHBRIDGE','OAKHAM','OXFORD','PAXTON','PRINCETON','RUTLAND','SHREWSBURY','SOUTHBRIDGE','SPENCER','STURBRIDGE','SUTTON','UPTON','UXBRIDGE','WARREN','WEBSTER','WEST BOYLSTON','WEST BROOKFIELD','WESTBOROUGH','WORCESTER','ASHBURNHAM','ASHBY','ATHOL','AYER','CLINTON','FITCHBURG','GARDNER','GROTON','HARVARD','HUBBARDSTON','LANCASTER','LEOMINSTER','LUNENBURG','PETERSHAM','PHILLIPSTON','ROYALSTON','SHIRLEY','STERLING','TEMPLETON','TOWNSEND','WESTMINSTER','WINCHENDON')"  data/grid_attr_filtCentral.geojson ../proc/grid_250m_shell_smaller_data.shp

ogr2ogr -f "GeoJSON" -s_srs "EPSG:2805" -t_srs "EPSG:4326" -where "municipal IN ('ADAMS','ALFORD','BECKET','CHESHIRE','CLARKSBURG','DALTON','EGREMONT','FLORIDA','GREAT BARRINGTON','HANCOCK','HINSDALE','LANESBOROUGH','LEE','LENOX','MONTEREY','MOUNT WASHINGTON','NEW ASHFORD','NEW MARLBOROUGH','NORTH ADAMS','OTIS','PERU','PITTSFIELD','RICHMOND','SANDISFIELD','SAVOY','SHEFFIELD','STOCKBRIDGE','TYRINGHAM','WASHINGTON','WEST STOCKBRIDGE','WILLIAMSTOWN','WINDSOR','ASHFIELD','BERNARDSTON','BUCKLAND','CHARLEMONT','COLRAIN','CONWAY','DEERFIELD','ERVING','GILL','GREENFIELD','HAWLEY','HEATH','LEVERETT','LEYDEN','MONROE','MONTAGUE','NEW SALEM','NORTHFIELD','ORANGE','ROWE','SHELBURNE','SHUTESBURY','SUNDERLAND','WARWICK','WENDELL','WHATELY','AGAWAM','AMHERST','BELCHERTOWN','BLANDFORD','BRIMFIELD','CHESTER','CHESTERFIELD','CHICOPEE','CUMMINGTON','EAST LONGMEADOW','EASTHAMPTON','GOSHEN','GRANBY','GRANVILLE','HADLEY','HAMPDEN','HATFIELD','HOLLAND','HOLYOKE','HUNTINGTON','LONGMEADOW','LUDLOW','MIDDLEFIELD','MONSON','MONTGOMERY','NORTHAMPTON','PALMER','PELHAM','PLAINFIELD','RUSSELL','SOUTH HADLEY','SOUTHAMPTON','SOUTHWICK','SPRINGFIELD','TOLLAND','WALES','WARE','WEST SPRINGFIELD','WESTFIELD','WESTHAMPTON','WILBRAHAM','WILLIAMSBURG','WORTHINGTON')" data/grid_attr_filtWestern.geojson ../proc/grid_250m_shell_smaller_data.shp
